spring.application.name=College_Placement_Management

spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/campus_hiring?createDatabaseIfNotExist=true&sslMode=VERIFY_IDENTITY&serverTimezone=UTC
spring.datasource.username=3xNXPZxmEthaeNc.root
spring.datasource.password=obiPXQdYm6Qaqq54
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Remove or leave as default (Hibernate 6+ auto-detects MySQL):
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

app.cors.allowed-origins=http://localhost:5173,http://localhost:3000
